import { entityTakeDamage } from "./MC_ENTITY_TAKE_DMG";
import { evalCache } from "./MC_EVALUATE_CACHE";
import { bombInit } from "./MC_POST_BOMB_INIT";
import { bombUpdate } from "./MC_POST_BOMB_UPDATE";
import { postFireTear } from "./MC_POST_FIRE_TEAR";
import { postNewRoom } from "./MC_POST_NEW_ROOM";
import { npcRender } from "./MC_POST_NPC_RENDER";
import { postPickupUpdate } from "./MC_POST_PICKUP_UPDATE";
import { postPlayerInit } from "./MC_POST_PLAYER_INIT";
import { projectileInit } from "./MC_POST_PROJECTILE_INIT";
import { preGameExit } from "./MC_PRE_GAME_EXIT";
import { preTearCollision } from "./MC_PRE_TEAR_COLLISION";
import { usePill } from "./MC_USE_PILL";

export { entityTakeDamage };
export { evalCache };
export { bombInit };
export { postFireTear };
export { postNewRoom };
export { npcRender };
export { postPickupUpdate };
export { postPlayerInit };
export { projectileInit };
export { preGameExit };
export { preTearCollision };
export { usePill };
export { bombUpdate };
