--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.ModItemTypes = ModItemTypes or ({})
____exports.ModItemTypes.FAT_FETUS = Isaac.GetItemIdByName("Fat Fetus")
____exports.ModItemTypes[____exports.ModItemTypes.FAT_FETUS] = "FAT_FETUS"
____exports.ModItemTypes.BLOODDRIVE = Isaac.GetItemIdByName("Blood Drive")
____exports.ModItemTypes[____exports.ModItemTypes.BLOODDRIVE] = "BLOODDRIVE"
____exports.ModItemTypes.GHOST_SHOT = Isaac.GetItemIdByName("Ghost Shot")
____exports.ModItemTypes[____exports.ModItemTypes.GHOST_SHOT] = "GHOST_SHOT"
____exports.ModItemTypes.BBGHOST_SHOT = Isaac.GetItemIdByName("Big Boy Ghost Shot")
____exports.ModItemTypes[____exports.ModItemTypes.BBGHOST_SHOT] = "BBGHOST_SHOT"
____exports.ModItemTypes.BLUE_HEART = Isaac.GetItemIdByName("Blue Heart")
____exports.ModItemTypes[____exports.ModItemTypes.BLUE_HEART] = "BLUE_HEART"
____exports.ModItemTypes.RUSSIANROULETTE = Isaac.GetItemIdByName("Russian Roulette")
____exports.ModItemTypes[____exports.ModItemTypes.RUSSIANROULETTE] = "RUSSIANROULETTE"
____exports.ModTearVariants = ModTearVariants or ({})
____exports.ModTearVariants.GHOST = 50
____exports.ModTearVariants[____exports.ModTearVariants.GHOST] = "GHOST"
____exports.ModEntityVariants = ModEntityVariants or ({})
____exports.ModEntityVariants.GHOST_TEAR = 50
____exports.ModEntityVariants[____exports.ModEntityVariants.GHOST_TEAR] = "GHOST_TEAR"
____exports.ModPlayerTypes = ModPlayerTypes or ({})
____exports.ModPlayerTypes.ALABASTER = Isaac.GetPlayerTypeByName("Alabaster")
____exports.ModPlayerTypes[____exports.ModPlayerTypes.ALABASTER] = "ALABASTER"
____exports.ModCostumes = ModCostumes or ({})
____exports.ModCostumes.ALABASTER_HAIR = Isaac.GetCostumeIdByPath("gfx/characters/c_Alabaster_Hair.anm2")
____exports.ModCostumes[____exports.ModCostumes.ALABASTER_HAIR] = "ALABASTER_HAIR"
____exports.game = Game()
____exports.sfxManager = SFXManager()
return ____exports
